import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { forkJoin, of, throwError } from 'rxjs';
import { catchError, finalize } from 'rxjs/operators';
import {
  WeeklyCollaborationReport,
  WeeklyCollaborationRiskLevel,
} from '../../../core/models/weekly-collaboration-report.model';
import {
  GlobalCollaborationInsight,
  MarketingCollaborationInsight,
  ResourceCollaborationInsight,
  WeeklyCollaborationAiReport,
} from '../../../core/models/weekly-collaboration-ai-report.model';
import { WeeklyCollaborationReportService } from '../../../core/services/weekly-collaboration-report.service';

interface WeeklyMetricCard {
  label: string;
  value: string;
  hint?: string;
  statusClass?: string;
}

@Component({
  selector: 'app-weekly-collaboration-report',
  templateUrl: './weekly-collaboration-report.component.html',
  styleUrls: ['./weekly-collaboration-report.component.css'],
})
export class WeeklyCollaborationReportComponent implements OnInit {
  viewMode: 'weekly-report' | 'ai-recommendations' = 'weekly-report';
  latestReport: WeeklyCollaborationReport | null = null;
  selectedReport: WeeklyCollaborationReport | null = null;
  reports: WeeklyCollaborationReport[] = [];

  selectedAiReport: WeeklyCollaborationAiReport | null = null;

  loading = false;
  generating = false;
  selectedReportLoading = false;
  aiPanelLoading = false;
  error = '';
  notice = '';
  aiErrorMessage = '';

  globalAiLoading = false;
  resourceAiLoading = false;
  marketingAiLoading = false;

  private readonly dateFormatter = new Intl.DateTimeFormat('en-GB', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  });

  private readonly dateTimeFormatter = new Intl.DateTimeFormat('en-GB', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  private readonly percentFormatter = new Intl.NumberFormat('en-GB', {
    style: 'percent',
    minimumFractionDigits: 0,
    maximumFractionDigits: 1,
  });

  private readonly collaborationTypeLabels: Record<string, string> = {
    MARKETING: 'Marketing',
    RESOURCES: 'Resources',
  };

  constructor(
    private route: ActivatedRoute,
    private weeklyReportService: WeeklyCollaborationReportService,
  ) {}

  ngOnInit(): void {
    this.route.data.subscribe(data => {
      this.viewMode = data['viewMode'] === 'ai-recommendations' ? 'ai-recommendations' : 'weekly-report';
    });
    this.loadDashboard();
  }

  get hasReports(): boolean {
    return !!this.latestReport || this.reports.length > 0;
  }

  get isWeeklyReportView(): boolean {
    return this.viewMode === 'weekly-report';
  }

  get isAiRecommendationsView(): boolean {
    return this.viewMode === 'ai-recommendations';
  }

  get pageTitle(): string {
    return this.isAiRecommendationsView ? 'AI Recommendations' : 'Weekly Report';
  }

  get pageSubtitle(): string {
    return this.isAiRecommendationsView
      ? 'Optional AI interpretation based on the selected backend report.'
      : 'Verified metrics generated by backend rules.';
  }

  generateCurrentWeekReport(): void {
    this.generating = true;
    this.error = '';
    this.notice = '';
    this.aiErrorMessage = '';

    this.weeklyReportService.generateReport()
      .pipe(finalize(() => { this.generating = false; }))
      .subscribe({
        next: report => {
          this.notice = 'The current week report was generated successfully.';
          this.latestReport = report;
          this.selectedReport = report;
          this.loadDashboard(report.id);
        },
        error: err => {
          this.error = this.toFriendlyError(err, 'Unable to generate the current week report right now.');
        },
      });
  }

  viewReport(report: WeeklyCollaborationReport): void {
    if (this.selectedReport?.id === report.id && !this.selectedReportLoading) {
      return;
    }

    this.selectedReportLoading = true;
    this.error = '';
    this.aiErrorMessage = '';

    this.weeklyReportService.getReportById(report.id)
      .pipe(finalize(() => { this.selectedReportLoading = false; }))
      .subscribe({
        next: detailedReport => {
          this.selectedReport = detailedReport;
          this.loadAiReportState(detailedReport.id);
        },
        error: err => {
          this.error = this.toFriendlyError(err, 'Unable to open that weekly report right now.');
        },
      });
  }

  generateGlobalAiReport(): void {
    const targetReportId = this.selectedReport?.id;

    if (!targetReportId) {
      this.aiErrorMessage = 'Generate or select a backend weekly report before generating AI insights.';
      return;
    }

    this.globalAiLoading = true;
    this.notice = '';
    this.aiErrorMessage = '';

    this.weeklyReportService.generateGlobalAiInsights(targetReportId)
      .pipe(finalize(() => { this.globalAiLoading = false; }))
      .subscribe({
        next: aiReport => {
          this.selectedAiReport = aiReport;
          this.notice = 'Global AI insights generated successfully.';
        },
        error: err => {
          const message = this.toFriendlyAiError(err);
          this.selectedAiReport = this.patchAiReport(targetReportId, {
            globalStatus: 'FAILED',
            globalError: message,
          });
        },
      });
  }

  generateResourceAiReport(): void {
    const targetReportId = this.selectedReport?.id;

    if (!targetReportId) {
      this.aiErrorMessage = 'Generate or select a backend weekly report before generating AI insights.';
      return;
    }

    this.resourceAiLoading = true;
    this.notice = '';
    this.aiErrorMessage = '';

    this.weeklyReportService.generateResourceAiInsights(targetReportId)
      .pipe(finalize(() => { this.resourceAiLoading = false; }))
      .subscribe({
        next: aiReport => {
          this.selectedAiReport = aiReport;
          this.notice = 'Resource AI insights generated successfully.';
        },
        error: err => {
          const message = this.toFriendlyAiError(err);
          this.selectedAiReport = this.patchAiReport(targetReportId, {
            resourceStatus: 'FAILED',
            resourceError: message,
          });
        },
      });
  }

  generateMarketingAiReport(): void {
    const targetReportId = this.selectedReport?.id;

    if (!targetReportId) {
      this.aiErrorMessage = 'Generate or select a backend weekly report before generating AI insights.';
      return;
    }

    this.marketingAiLoading = true;
    this.notice = '';
    this.aiErrorMessage = '';

    this.weeklyReportService.generateMarketingAiInsights(targetReportId)
      .pipe(finalize(() => { this.marketingAiLoading = false; }))
      .subscribe({
        next: aiReport => {
          this.selectedAiReport = aiReport;
          this.notice = 'Marketing AI insights generated successfully.';
        },
        error: err => {
          const message = this.toFriendlyAiError(err);
          this.selectedAiReport = this.patchAiReport(targetReportId, {
            marketingStatus: 'FAILED',
            marketingError: message,
          });
        },
      });
  }

  trackByReport(_: number, report: WeeklyCollaborationReport): number {
    return report.id;
  }

  getRiskBadgeClass(riskLevel?: WeeklyCollaborationRiskLevel | null): string {
    switch (riskLevel) {
      case 'HIGH':
        return 'kh-badge--red';
      case 'MEDIUM':
        return 'kh-badge--amber';
      default:
        return 'kh-badge--green';
    }
  }

  getAiStatusBadgeClass(status?: WeeklyCollaborationAiReport['globalStatus'] | null): string {
    switch (status) {
      case 'SUCCESS':
        return 'kh-badge--green';
      case 'FAILED':
        return 'kh-badge--red';
      case 'PENDING':
        return 'kh-badge--amber';
      default:
        return 'kh-badge--teal';
    }
  }

  formatPeriod(report: WeeklyCollaborationReport | null): string {
    if (!report) {
      return 'No report selected';
    }

    return `${this.formatDateOnly(report.weekStartDate)} -> ${this.formatDateOnly(report.weekEndDate)}`;
  }

  formatDateOnly(value?: string | null): string {
    if (!value) {
      return 'Not available';
    }

    const parts = value.split('-').map(part => Number(part));
    if (parts.length === 3 && parts.every(part => Number.isFinite(part))) {
      return this.dateFormatter.format(new Date(parts[0], parts[1] - 1, parts[2]));
    }

    const fallbackDate = new Date(value);
    return Number.isNaN(fallbackDate.getTime()) ? value : this.dateFormatter.format(fallbackDate);
  }

  formatDateTime(value?: string | null): string {
    if (!value) {
      return 'Not available';
    }

    const date = new Date(value);
    return Number.isNaN(date.getTime()) ? value : this.dateTimeFormatter.format(date);
  }

  formatAiGeneratedAt(report?: WeeklyCollaborationAiReport | null): string {
    return report?.generatedAt ? this.formatDateTime(report.generatedAt) : 'Not available yet';
  }

  formatPercent(value?: number | null): string {
    return this.percentFormatter.format(value ?? 0);
  }

  formatClosedThisWeek(value: number): string {
    return `${value}`;
  }

  getLatestSnapshotCards(report?: WeeklyCollaborationReport | null): WeeklyMetricCard[] {
    if (!report) {
      return [];
    }

    return [
      this.metricCard('Active', this.formatWholeNumber(this.global(report).activeCollaborations)),
      this.metricCard('Pending', this.formatWholeNumber(this.global(report).pendingCollaborationRequests)),
      this.metricCard(
        'Resource backlog',
        this.formatPercent(this.resource(report).resourceBacklogRate),
        undefined,
        this.getResourceBacklogStatusClass(report)
      ),
      this.metricCard(
        'Overdue tasks',
        this.formatWholeNumber(this.marketing(report).overdueMarketingTasks),
        undefined,
        this.getOverdueTaskStatusClass(report)
      ),
    ];
  }

  getGlobalHealthCards(report?: WeeklyCollaborationReport | null): WeeklyMetricCard[] {
    if (!report) {
      return [];
    }

    return [
      this.metricCard('Active', this.formatWholeNumber(this.global(report).activeCollaborations)),
      this.metricCard(
        'Suspended',
        this.formatWholeNumber(this.global(report).suspendedCollaborations),
        undefined,
        this.global(report).suspendedCollaborations > 0 ? 'weekly-report-kpi--warning' : undefined
      ),
      this.metricCard('Closed', this.formatWholeNumber(this.global(report).closedCollaborations)),
      this.metricCard('Created this week', this.formatWholeNumber(this.global(report).collaborationsCreatedThisWeek)),
      this.metricCard('Closed this week', this.formatClosedThisWeek(report.collaborationsClosedThisWeek)),
    ];
  }

  getRequestMembershipCards(report?: WeeklyCollaborationReport | null): WeeklyMetricCard[] {
    if (!report) {
      return [];
    }

    return [
      this.metricCard('Pending', this.formatWholeNumber(this.global(report).pendingCollaborationRequests)),
      this.metricCard('Accepted', this.formatWholeNumber(this.global(report).acceptedRequestsThisWeek)),
      this.metricCard('Rejected', this.formatWholeNumber(this.global(report).rejectedRequestsThisWeek)),
      this.metricCard('New members', this.formatWholeNumber(this.global(report).newMembersThisWeek)),
      this.metricCard(
        'Request conversion',
        this.formatPercent(this.global(report).requestConversionRate),
        undefined,
        this.global(report).requestConversionRate < 0.3 ? 'weekly-report-kpi--danger' : undefined
      ),
      this.metricCard('Invitation acceptance', this.formatPercent(this.global(report).invitationAcceptanceRate)),
    ];
  }

  getResourceAnalysisCards(report?: WeeklyCollaborationReport | null): WeeklyMetricCard[] {
    if (!report) {
      return [];
    }

    return [
      this.metricCard('Open', this.formatWholeNumber(this.resource(report).openResourceRequests)),
      this.metricCard('Fulfilled', this.formatWholeNumber(this.resource(report).fulfilledResourceRequests)),
      this.metricCard('Cancelled', this.formatWholeNumber(this.resource(report).cancelledResourceRequests)),
      this.metricCard(
        'Backlog rate',
        this.formatPercent(this.resource(report).resourceBacklogRate),
        undefined,
        this.getResourceBacklogStatusClass(report)
      ),
      this.metricCard(
        'Fulfillment rate',
        this.formatPercent(this.resource(report).resourceFulfillmentRate)
      ),
    ];
  }

  getMarketingAnalysisCards(report?: WeeklyCollaborationReport | null): WeeklyMetricCard[] {
    if (!report) {
      return [];
    }

    return [
      this.metricCard('Active campaigns', this.formatWholeNumber(this.marketing(report).activeMarketingCampaigns)),
      this.metricCard('Completed campaigns', this.formatWholeNumber(this.marketing(report).completedMarketingCampaigns)),
      this.metricCard(
        'Overdue tasks',
        this.formatWholeNumber(this.marketing(report).overdueMarketingTasks),
        undefined,
        this.getOverdueTaskStatusClass(report)
      ),
      this.metricCard(
        'Overdue ratio',
        this.formatPercent(this.marketing(report).overdueTaskRatio),
        undefined,
        this.getOverdueTaskStatusClass(report)
      ),
      this.metricCard(
        'Execution rate',
        this.formatPercent(this.marketing(report).marketingExecutionRate)
      ),
    ];
  }

  getCollaborationTypeEntries(report?: WeeklyCollaborationReport | null): Array<{ key: string; label: string; value: number }> {
    const byType = this.global(report).collaborationsByType ?? report?.collaborationsByType ?? {};

    return Object.keys(byType)
      .sort((left, right) => left.localeCompare(right))
      .filter(key => (byType[key] ?? 0) > 0)
      .map(key => ({
        key,
        label: this.collaborationTypeLabels[key] ?? key,
        value: byType[key] ?? 0,
      }));
  }

  hasPreparedAiReport(report?: WeeklyCollaborationAiReport | null): boolean {
    return !!report && report.id > 0;
  }

  hasGlobalInsight(report?: WeeklyCollaborationAiReport | null): boolean {
    return !!report?.globalInsight;
  }

  hasResourceInsight(report?: WeeklyCollaborationAiReport | null): boolean {
    return !!report?.resourceInsight;
  }

  hasMarketingInsight(report?: WeeklyCollaborationAiReport | null): boolean {
    return !!report?.marketingInsight;
  }

  hasAnyInsight(report?: WeeklyCollaborationAiReport | null): boolean {
    return this.hasGlobalInsight(report) || this.hasResourceInsight(report) || this.hasMarketingInsight(report);
  }

  getGlobalActionLabel(report?: WeeklyCollaborationAiReport | null): string {
    return this.hasGlobalInsight(report) ? 'Regenerate Global' : 'Generate Global';
  }

  getResourceActionLabel(report?: WeeklyCollaborationAiReport | null): string {
    return this.hasResourceInsight(report) ? 'Regenerate Resource' : 'Generate Resource';
  }

  getMarketingActionLabel(report?: WeeklyCollaborationAiReport | null): string {
    return this.hasMarketingInsight(report) ? 'Regenerate Marketing' : 'Generate Marketing';
  }

  formatInsightValue(value?: string | null, fallback = 'Unavailable'): string {
    return value?.trim() || fallback;
  }

  getInsightActions(actions?: string[] | null): string[] {
    return (actions ?? []).filter(action => !!action?.trim());
  }

  getAiValueBadgeClass(value?: string | null): string {
    switch ((value ?? '').toUpperCase()) {
      case 'BLOCKED':
      case 'HIGH':
      case 'CRITICAL':
      case 'POOR':
        return 'kh-badge--red';
      case 'STAGNANT':
      case 'SLOW':
      case 'MEDIUM':
      case 'PARTIAL':
      case 'DEGRADED':
        return 'kh-badge--amber';
      case 'HEALTHY':
      case 'SMOOTH':
      case 'LOW':
      case 'GOOD':
      case 'SUCCESS':
        return 'kh-badge--green';
      default:
        return 'kh-badge--teal';
    }
  }

  private loadDashboard(preferredReportId?: number): void {
    this.loading = true;
    this.error = '';

    forkJoin({
      latest: this.weeklyReportService.getLatestReport().pipe(
        catchError(err => {
          if (err?.status === 404) {
            return of(null);
          }

          return throwError(() => new Error(
            this.toFriendlyError(err, 'Unable to load weekly reports right now.')
          ));
        })
      ),
      reports: this.weeklyReportService.getAllReports().pipe(
        catchError(err => throwError(() => new Error(
          this.toFriendlyError(err, 'Unable to load weekly reports right now.')
        )))
      ),
    })
      .pipe(finalize(() => { this.loading = false; }))
      .subscribe({
        next: ({ latest, reports }) => {
          this.latestReport = latest;
          this.reports = reports ?? [];

          if (!this.latestReport && !this.reports.length) {
            this.selectedReport = null;
            this.selectedAiReport = null;
            return;
          }

          const preferredReport = preferredReportId
            ? this.reports.find(report => report.id === preferredReportId) ?? null
            : null;

          this.selectedReport = preferredReport ?? this.latestReport ?? this.reports[0] ?? null;
          this.loadAiReportState(this.selectedReport?.id ?? null);
        },
        error: err => {
          this.latestReport = null;
          this.selectedReport = null;
          this.selectedAiReport = null;
          this.reports = [];
          this.error = err instanceof Error
            ? err.message
            : 'Unable to load weekly reports right now.';
        },
      });
  }

  private loadAiReportState(reportId: number | null): void {
    if (!reportId) {
      this.selectedAiReport = null;
      return;
    }

    this.aiPanelLoading = true;
    this.aiErrorMessage = '';

    this.weeklyReportService.getAiReports(reportId)
      .pipe(finalize(() => { this.aiPanelLoading = false; }))
      .subscribe({
        next: aiReports => {
          this.selectedAiReport = aiReports[0] ?? this.createEmptyAiReport(reportId);
        },
        error: err => {
          const message = this.toFriendlyAiError(err);
          this.aiErrorMessage = message;
          this.selectedAiReport = this.patchAiReport(reportId, {});
        },
      });
  }

  private syncReportState(report: WeeklyCollaborationReport): void {
    if (!this.reports.some(existingReport => existingReport.id === report.id)) {
      this.reports = [report, ...this.reports];
    } else {
      this.reports = this.reports.map(existingReport => existingReport.id === report.id ? report : existingReport);
    }

    if (this.latestReport?.id === report.id) {
      this.latestReport = report;
    }

    if (this.selectedReport?.id === report.id || !this.selectedReport) {
      this.selectedReport = report;
    }
  }

  private createEmptyAiReport(reportId: number): WeeklyCollaborationAiReport {
    return {
      id: 0,
      weeklyReportId: reportId,
      generatedAt: null,
      globalInsightJson: null,
      globalStatus: null,
      globalError: null,
      resourceInsightJson: null,
      resourceStatus: null,
      resourceError: null,
      marketingInsightJson: null,
      marketingStatus: null,
      marketingError: null,
      globalInsight: null,
      resourceInsight: null,
      marketingInsight: null,
    };
  }

  private patchAiReport(reportId: number, patch: Partial<WeeklyCollaborationAiReport>): WeeklyCollaborationAiReport {
    const base = this.selectedAiReport?.weeklyReportId === reportId
      ? this.selectedAiReport
      : this.createEmptyAiReport(reportId);

    return { ...base, ...patch };
  }

  private toFriendlyError(err: any, fallbackMessage: string): string {
    const status = err?.status;

    if (status === 403) {
      return 'You do not have permission to access weekly collaboration reports.';
    }

    if (status === 404) {
      return 'No weekly collaboration report is available yet.';
    }

    if (status === 0) {
      return 'The weekly reports service is currently unreachable. Please try again in a moment.';
    }

    return fallbackMessage;
  }

  private toFriendlyAiError(err: any): string {
    const status = err?.status;

    if (status === 403) {
      return 'You do not have permission to generate AI weekly insight reports.';
    }

    if (status === 404) {
      return 'The selected backend report could not be found anymore.';
    }

    if (status === 0) {
      return 'The AI insight service is currently unreachable. Please try again in a moment.';
    }

    return 'The AI weekly insight report is unavailable right now. Please try again in a moment.';
  }

  private global(report?: WeeklyCollaborationReport | null) {
    return report?.globalCollaborationHealth ?? {
      collaborationsCreatedThisWeek: report?.collaborationsCreatedThisWeek ?? 0,
      activeCollaborations: report?.activeCollaborations ?? 0,
      suspendedCollaborations: report?.suspendedCollaborations ?? 0,
      closedCollaborations: report?.closedCollaborations ?? 0,
      pendingCollaborationRequests: report?.pendingCollaborationRequests ?? 0,
      acceptedRequestsThisWeek: report?.acceptedRequestsThisWeek ?? 0,
      rejectedRequestsThisWeek: report?.rejectedRequestsThisWeek ?? 0,
      newMembersThisWeek: report?.newMembersThisWeek ?? 0,
      invitationsSentThisWeek: report?.invitationsSentThisWeek ?? 0,
      invitationsAcceptedThisWeek: report?.invitationsAcceptedThisWeek ?? 0,
      invitationsRejectedThisWeek: report?.invitationsRejectedThisWeek ?? 0,
      collaborationsByType: report?.collaborationsByType ?? {},
      requestConversionRate: 0,
      invitationAcceptanceRate: 0,
    };
  }

  private resource(report?: WeeklyCollaborationReport | null) {
    return report?.resourceCollaborationAnalysis ?? {
      openResourceRequests: report?.openResourceRequests ?? 0,
      fulfilledResourceRequests: report?.fulfilledResourceRequests ?? 0,
      cancelledResourceRequests: report?.cancelledResourceRequests ?? 0,
      totalResourceRequests: (report?.openResourceRequests ?? 0)
        + (report?.fulfilledResourceRequests ?? 0)
        + (report?.cancelledResourceRequests ?? 0),
      resourceFulfillmentRate: 0,
      resourceBacklogRate: 0,
    };
  }

  private marketing(report?: WeeklyCollaborationReport | null) {
    return report?.marketingCollaborationAnalysis ?? {
      activeMarketingCampaigns: report?.activeMarketingCampaigns ?? 0,
      completedMarketingCampaigns: report?.completedMarketingCampaigns ?? 0,
      overdueMarketingTasks: report?.overdueMarketingTasks ?? 0,
      publishedMarketingTasks: report?.publishedMarketingTasks ?? 0,
      totalMarketingTasks: report?.totalMarketingTasks ?? 0,
      overdueTaskRatio: 0,
      marketingExecutionRate: 0,
    };
  }

  private metricCard(label: string, value: string, hint?: string, statusClass?: string): WeeklyMetricCard {
    return { label, value, hint, statusClass };
  }

  private formatWholeNumber(value: number): string {
    return `${value}`;
  }

  private getResourceBacklogStatusClass(report: WeeklyCollaborationReport): string | undefined {
    const backlogRate = this.resource(report).resourceBacklogRate;
    if (backlogRate > 0.5) {
      return 'weekly-report-kpi--danger';
    }

    if (backlogRate > 0.3) {
      return 'weekly-report-kpi--warning';
    }

    return undefined;
  }

  private getOverdueTaskStatusClass(report: WeeklyCollaborationReport): string | undefined {
    const overdueTaskRatio = this.marketing(report).overdueTaskRatio;
    if (overdueTaskRatio > 0.3) {
      return 'weekly-report-kpi--danger';
    }

    if (overdueTaskRatio > 0.15) {
      return 'weekly-report-kpi--warning';
    }

    return undefined;
  }
}
